apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-api
  labels:
    app: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: zolda/todo-api:1.0.0
        ports:
        - containerPort: 80
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: todo-api-secret-prod
              key: DATABASE_URL
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: 20s
      - setWeight: 50
      - pause:
          duration: 20s
      - setWeight: 100
