---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-api-secret
  namespace: todo-api-prod
spec:
  encryptedData:
    DATABASE_URL: AgCBRi6vOQabRTkfViUOodx4z7KPSZVFiS/PXdUqBmyZ0P+o6K8YJfCJs4YAkOWRpoayFZkM3u2eEQeTMB9Qxmib8LJchFkf4QQj/nABwJ+C+HL9tt8XyMiY0KUsMmtIMZAB/kdVyxYQl2F7za8kVvc7zmAzfEaKKxMHMadaqcn/MLin163bJAshxyFRQk4k92qjrkdjq0P8PqEWV6lNzOn87LnRaF/zXl3u7oDJfUlSij65t3FYbvcR2AYDKcPpAd5QNt5XflwBIHj24gQp1bMutvaed1FZ9H8C5hXpQPkhG5yyK43SRCCVoeQQbMOSdKJvbSLYidQuz3qvxszQnsDhZsddDbHgl3PgIJAZ2jFLNmbW1x5uSEcbK147tsng4iA8Rk2aucbC/msw6bIXJBiGGh5w9W0C5lyhxnvNuJtjtyI2npEZZ2rhpDu9+HzIkg1H6gS0OiJLF6L0oYRX1F4grHhSAaxHzB74VwuqxN9rUYOLRsd5x2EqpVe6l6cKq9u7V+AbIBJkw+qJSR7FM8PGUOv6N7w86E4QBBFUZgMcuFztNPdKvKB5ftUQPSXxREmsqGMwafpGUl/ZoUxrs/HVeO+o6NomaS9izqh0Rurcehxz+ipjan98P9KFTd+KFVxEx3zmGrH7cjxb6Qf0dudkqbeROphR3ba0FtviyfgoAtQNPW2iQ/KUK6eTiXiSkO2JQaU7fE3aHH5KYoiVGtlv2wiSCci2ktF19EtS3CH+zP+XZascbdX6ZKyNhgxWEyYfomWn
  template:
    metadata:
      name: todo-api-secret
      namespace: todo-api-prod
