apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-api-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/souaibou18/gitops-souaibou
    targetRevision: HEAD
    path: apps/todo-api/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-api-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
