apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-api-prod

resources:
  - ../../base

nameSuffix: -prod

commonLabels:
  environment: prod

replicas:
  - name: todo-api
    count: 3
