apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-api-prod

resources:
- ../../base

nameSuffix: -prod

labels:
- includeSelectors: true
  pairs:
    environment: prod

patches:
- path: patch-replicas.yaml
images:
- name: nginx
  newName: nginx
  newTag: "1.25"
