---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-api-secret
  namespace: todo-api-prod
spec:
  encryptedData:
    DATABASE_URL: AgAl47tXedOVssSwLmN0Got0+wyQOmCYaxgQr+Kej0JF/zB0j0HCwjw4w9ysUyKfK23uxB691/pKfy1+/uyhPeIjKYTjUo899lfRfV0tfws6R4aMdKIMW5LQucnTIKrQon3scOPkAPiPu4OlFgY7RF+GEj6yNgTMtX1o+RCnCX5YRMxu0cjmQW3U1t/3xtCuqGKwYEgsi8uSDElWZ2jj2AoopNPx1+DO69drd3hrR1Nsi7xmXIpT5wRaJtzDdDtzxntP8wokcmisz4dv0zQQv1G4crpOXOCEIpru6SJ7/342p5c3uLJi4HC4OCVwqOevjwOFjPwhzu4b+Mc1SsNeH1a9e1uNjLwKi7/W26tSCR7JQt0dGsOOoSgBhzsSg8tTlD/A6UTa2BLiAUgyLzU+7o1IVL4xtH5dlA+ALR0+qwIh6xh7LV8GyqrTyr9C3DSTR2CgEK8zgmG8/m+MtYj8BJPeNkFf/pnhbbKd6ScAy860fnk07yJkJcI0wDw3O+pAFyn5QpJkClcYsU64WrastjlfopHVUcUwf9eCF+RRbbZHrAbV0NOzDCBKcqJMQ+0n1UMy/ayoD1S4gAr5uMk5EJRp/8YWKONaiIELgh6yqh7PO5KrJbFLiJi4A7Ep7EYq4M9Y2GWrRq9Pf3QwlsVcp8vAS13+7ip2AiqDyZPJ7edhZ3s/uEaSypWrx0/msAgZdjPx6xk1a57eNOKzIT/BRNSdq4Ji6pHxBfKIVLzLXSEdc8WQTIIYGhFyWNhPJ93/P6pN8FfQ
  template:
    metadata:
      name: todo-api-secret
      namespace: todo-api-prod
