---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-api-secret-prod
  namespace: todo-api-prod
spec:
  encryptedData:
    DATABASE_URL: AgBVux4m5vQAQJNRFXwJtp/tW1x0ETcRsR3pcZiIJ/sGOBkPPnsixCabZpHWs4hPSIoEBBSNryZkUDBWRSJYzB92dTZZhHS7jzu+D7z2PXvDQaKdV5HReTj8RfnyrAKZgrRcwPy6UkFXu7/2H8ihzHOffbjI1UX2g0dONYEqfiMBR5baSlXXUqcvNjX+YJFD27AbZY4RsZ4UCs/BO9io2RJwh144XvRq57vNEZmNftivuuNjhy61Ju9qq9syidY6cctIFfF9RaQDWrZ5Bbp6mY02ysKvGmEvimbfFv8gTym0hQJUs8PvDglQAf6NRFmT/U9SkwXV5VQ6kHVCqA945tUpOHfkUlXbCmCHW6EmUIzKaBCIOH+TBzo8gF9ijyyNJQky6mGKrcEdgx9xA/oAdeBaVL68mDdADJA38ncGa/eY0YFTgc975ayrj4oSZhf5ofG2YRz+Gmrhz1uY5A9i3nDQiToQh8A7wtJJDaBf3gsXvHrB83HDKf3RPYGyn7nI4F3U3SiAzjGL3YDhM4pe2DMh8XI5lQoxAgb2cll58kclcRO3oIb1WfG+t6neC7kezlGgP2KLU/LVUsKGCMVN8MjxTOGGozOSzTTdwsvLftvQY/T7dPjZn8zBzDf8oNvZcsG+Kz26WEib2w/Se5GkTee1+c1XSTPTnPiRaKTK7uROt0KMU1+1sssBFqRse2ZNkjnpdG5HErNhf/0kF1YD597JY0DAQB0xtYHvkY2HMbjQKmKBOp9bl+VL2DhYHgXrourPn80w
  template:
    metadata:
      name: todo-api-secret-prod
      namespace: todo-api-prod
