---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-api-secret-prod
  namespace: todo-api-prod
spec:
  encryptedData:
    DATABASE_URL: AgCMkoo1g4ma9uFuI/872jEZ+MDOxd6C0pbF8LK8nWOZqbqbxj91+P8+BS6alKr+WpaeXzoitDuXi7pey3J7PMcujhBVLGFThz2pks8sDNAjWUR0Orz0UR+XzT443N2IN0NO/F1C1b5LrkVE09TA3BK0FhpXKdRLvdiqs6ZlBVHsJKa86XfW0nW1VT60FdajXy3xg+6x23/Iqe72sDyhUbER0CaGD+khHEnUNCAJL+ogdT/YQ7CjpC9Bpzs2i9PYmmBwOCR2T5+LZW69zOlsSXos7YjgWY+kt1yhoBeCKUHm8WFrimOXCL4U1dRIJBA4TZ7xABHSY/70o4DmzRfVsIqwZIjDqvRB3jKKtYqNTB9hhFreQbPO9g6nQw8YbB3W0RDdmn1yDpv2gqtmig6Lk3at5qoNNK9p6bZleKmHkQkoB/avi303AG9KJ9KpCdOPAuNgOk6Rq0AwrNXvse3wJ2HpQrqvm6KvLtaYvbI3evtZy3e86De9clLr1qBU8HSAvXX8enlbkSdHcfM9SOfpXlS6fSJIdjznJw+zl8XXiWSj0PAqGGNGWe1daiTQGZlvRghBJgXrXM4Iko7a2X5Gsf8TWHiY429kNCsUnWHSF//TwW+YMw2loqQIlxKeKbZor+rQYN0ZzdXmqkim40PaegczCPzV9B1TS58PifaZTD/4GrDpS2tF8SblSH+LYbvns5fxvQTj2Ob7yUtL1anJACM1zl768cpvmBmOkb1jPODwToKCkmuqxUonHMIrFawwQgZ/NAio
  template:
    metadata:
      name: todo-api-secret-prod
      namespace: todo-api-prod
